title: Frédéric Clavert
author: Frédéric Clavert
description: (Digital) Historian
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_downloads: false

collections:
  blog:
    output: true
    permalink: /content/blog/:name

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "default"

feed:
  collections:
    blog:
      path: "/blog.xml"
